# Generated by Django 4.1.1 on 2022-12-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('max_temp', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('rain', models.IntegerField()),
            ],
            options={
                'db_table': 'weather_data',
            },
        ),
        migrations.CreateModel(
            name='WeatherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('avg_min_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_max_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_rain', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'weather_stats',
            },
        ),
    ]
